[agent]
uid = my-agent-002
server_host = xdev.arkcom.ru
server_port = 9999
base_path = /app/webagent1/api
task_interval = 30
tasks_dir = tasks
results_dir = results
access_code = 7fa04c-ece8-a61d-2712-cc823c2c
log_level = debug

[client]
uid = my-agent-002
server_host = xdev.arkcom.ru
server_port = 9999
base_path = /app/webagent1/api
access_code = 7fa04c-ece8-a61d-2712-cc823c2c
log_level = debug